import React, { useState } from 'react';
import { Editor, Markdown } from './ui.jsx';
import { useDraft } from './client.js';
import { Authority, AuthorityFields, ClaimNotice, DetailTop, lines, PlanningConflict, References, SourceIssues, SourcePicker, SourceVersions, authorityDraft } from './planning.jsx';

const specDraft = item => ({ baseRev: item.rev, title: item.title, markdown: item.markdown, mapId: item.mapId || '', questionIds: item.questionIds, references: item.references.join('\n') });
const questionSnapshot = (ids, questions) => ids.map(questionId => { const question = questions.find(question => question.id === questionId); return { questionId, answerId: question?.state === 'resolved' ? question.answer?.id ?? null : null, revision: question?.state === 'resolved' ? question.answer?.revision ?? null : null }; });
export function SpecDetail({ workspaceId, item, revisions, questions, maps, mutate, busy, expanded, onExpand, onClose, onQuestion, onBoard }) {
  const key = `wayfinder:spec:${workspaceId}:${item.id}`;
  const [draft, setDraft, storage] = useDraft(`${key}:content`), [approval, setApproval, approvalStorage] = useDraft(`${key}:approval`);
  const [error, setError] = useState(''), [saved, setSaved] = useState('');
  async function act(op, input, completion) {
    setError(''); setSaved('');
    try { await mutate(op, input, () => setSaved('Saved'), completion); } catch (problem) { setError(problem.message); }
  }
  const finish = (suffix, submitted) => ({ draft: { key: `${key}:${suffix}`, submitted } });
  return <section className="detail planning-detail" aria-label={`Spec details for ${item.id}`}><DetailTop item={item} expanded={expanded} onExpand={onExpand} onClose={onClose} noun="spec"/><div className="detail-content"><div className="detail-kicker"><span>Implementation spec</span><span className="execution-state">{item.state === 'approved' ? 'Approved' : 'Draft'}</span></div><h2>{item.title}</h2><div className="metadata"><span>{maps.find(map => map.id === item.mapId)?.title || 'Workspace spec'}</span><span>Approval {item.acceptedRevision ?? 'none'}</span><span>{item.usableApproval ? 'Current approval' : 'Approval needed'}</span></div><button className="quiet-button" onClick={() => onBoard(item.id)}>View tickets for this spec</button>{error ? <p className="form-error action-error" role="alert">{error}</p> : null}{saved ? <p className="save-status" role="status">{saved}</p> : null}{storage || approvalStorage ? <p className="form-error">Browser draft storage is unavailable. Save or copy this draft before reloading.</p> : null}<ClaimNotice item={item} type="spec" busy={busy} act={act}/><SourceIssues issues={item.sourceIssues}/><div className="section-heading"><h3>Spec draft</h3><button className="quiet-button" disabled={busy || Boolean(draft)} onClick={() => setDraft(specDraft(item))}>Edit draft</button></div>
    {draft ? <form className="planning-fields" onSubmit={event => { event.preventDefault(); act('spec.update', { specId: item.id, expectedRev: draft.baseRev, patch: { title: draft.title, markdown: draft.markdown, mapId: draft.mapId || null, questionIds: draft.questionIds, references: lines(draft.references) } }, finish('content', draft)); }}><p className="muted content-note">Saving changes returns the spec to Draft. Earlier approval revisions stay in history and linked tickets require review.</p><label>Spec title<input required maxLength={300} disabled={busy} value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })}/></label><Editor label="Spec Markdown" disabled={busy} value={draft.markdown} onChange={markdown => setDraft({ ...draft, markdown })}/><label>Map<select value={draft.mapId} disabled={busy} onChange={event => setDraft({ ...draft, mapId: event.target.value })}><option value="">Workspace-wide</option>{maps.map(map => <option key={map.id} value={map.id}>{map.title}</option>)}</select></label><SourcePicker maps={maps} questions={questions} mapId={draft.mapId} questionIds={draft.questionIds} onChange={questionIds => setDraft({ ...draft, questionIds })} disabled={busy}/><label>Artifact references, one per line<textarea disabled={busy} value={draft.references} onChange={event => setDraft({ ...draft, references: event.target.value })}/></label><PlanningConflict draft={draft} item={item} onReload={() => setDraft(specDraft(item))} onMerge={() => setDraft({ ...draft, baseRev: item.rev })}/><div className="editor-actions"><button className="button" type="button" disabled={busy} onClick={() => setDraft(null)}>Discard spec draft</button><button className="button primary" disabled={busy || draft.baseRev !== item.rev} type="submit">Save spec draft</button></div></form> : <><Markdown value={item.markdown || 'Write the scope, intended behavior, and acceptance criteria.'}/><References values={item.references}/></>}
    <div className="section-heading"><h3>Source questions</h3></div>{item.questionIds.map(id => { const question = questions.find(question => question.id === id); return <button className="source-link" key={id} disabled={!question} onClick={() => onQuestion(question)}><span>{question?.title || id}</span><span>{maps.find(map => map.id === question?.mapId)?.title || question?.mapId} · {question?.state === 'resolved' ? `Accepted answer ${question.answer?.revision}` : question?.state || 'Unavailable'}</span></button>; })}{!item.questionIds.length ? <p className="muted content-note">No source questions. Approval can cover a standalone spec.</p> : null}
    {!approval ? <button className="button primary" disabled={busy || Boolean(draft)} onClick={() => setApproval({ baseRev: item.rev, questionSources: questionSnapshot(item.questionIds, questions), authority: authorityDraft(null) })}>{item.acceptedRevision ? 'Record a new approval' : 'Approve spec'}</button> : <form className="answer-form planning-fields" onSubmit={event => { event.preventDefault(); act('spec.approve', { specId: item.id, expectedRev: approval.baseRev, questionSources: approval.questionSources, authority: approval.authority }, finish('approval', approval)); }}><h3>Record spec approval</h3><p className="muted content-note">Approval accepts the saved spec and these exact answer revisions.</p><SourceVersions sources={approval.questionSources} questions={questions}/><AuthorityFields value={approval.authority} onChange={authority => setApproval({ ...approval, authority })} disabled={busy}/><PlanningConflict draft={approval} item={item} onMerge={() => setApproval({ ...approval, baseRev: item.rev, questionSources: questionSnapshot(item.questionIds, questions) })} mergeLabel="Review latest spec and source revisions"/><div className="editor-actions"><button className="button" type="button" disabled={busy} onClick={() => setApproval(null)}>Discard approval draft</button><button type="submit" className="button primary" disabled={busy || Boolean(draft) || approval.baseRev !== item.rev}>Confirm spec approval</button></div></form>}
    <details className="answer-history"><summary>Spec approval history · {revisions.length}</summary>{revisions.toSorted((a, b) => b.revision - a.revision).map(revision => <article key={revision.revision}><div className="section-heading"><h3>Approval revision {revision.revision}</h3><span>{revision.revision === item.acceptedRevision ? 'Latest approval' : 'Earlier approval'}</span></div><h3>{revision.title}</h3><Markdown value={revision.markdown}/><Authority value={revision.authority}/><References values={revision.references}/><details><summary>Accepted source revisions</summary><SourceVersions sources={revision.questionSources} questions={questions}/></details></article>)}</details>
  </div></section>;
}
