import React, { useEffect, useRef, useState } from 'react';
import { Editor, Icon, Markdown } from './ui.jsx';
import { useDraft } from './client.js';
import { ticketMetadataChange } from './ticket-editing.js';
import { Authority, AuthorityFields, ClaimNotice, currentSources, DetailTop, lines, MOVES, PlanningConflict, References, SourceIssues, SourcePicker, SourceVersions, STATES, TicketFlags, TicketHistory, authorityDraft } from './planning.jsx';

const contentDraft = item => ({ baseRev: item.rev, title: item.title, body: item.body, acceptanceCriteria: item.acceptanceCriteria, authority: authorityDraft(item.authority), authorityEnabled: Boolean(item.authority) });
const progressDraft = item => ({ baseRev: item.rev, labels: item.labels.join(', '), priority: item.priority, progress: item.progress || '', references: item.references.join('\n') });

export function TicketDetail({ workspaceId, item, tickets, specs, questions, maps, links, query, mutate, busy, onSelect, onMove, onQuestion, onSpec, expanded, onExpand, onClose, moveIntent, clearMoveIntent }) {
  const key = `wayfinder:ticket:${workspaceId}:${item.id}`;
  const [draft, setDraft, contentStorage] = useDraft(`${key}:content`);
  const [progress, setProgress, progressStorage] = useDraft(`${key}:progress`);
  const [action, setAction, actionStorage] = useDraft(`${key}:action`);
  const [error, setError] = useState(''), [saved, setSaved] = useState('');
  const [relation, setRelation] = useState('blocked-by'), [target, setTarget] = useState('');
  const actionRef = useRef(null);
  useEffect(() => { if (action) actionRef.current?.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); }, [Boolean(action)]);
  const locked = !['backlog', 'ready'].includes(item.state);
  const metadataChange = ticketMetadataChange(item, progress);
  const deferredProgress = metadataChange.requiresReopen;
  const connections = links.filter(link => link.from === item.id || link.to === item.id);
  useEffect(() => {
    if (!moveIntent || moveIntent.ticketId !== item.id) return;
    if (action) setError('A saved action draft is open below. Finish or discard it before another move.');
    else setAction({ kind: 'transition', baseRev: moveIntent.baseRev, to: moveIntent.to, reason: '', markdown: '', references: '' });
    clearMoveIntent();
  }, [moveIntent, item.id]);
  async function act(op, input, completion, done) {
    setError(''); setSaved('');
    try { return await mutate(op, input, value => { setSaved('Saved'); done?.(value); }, completion); }
    catch (problem) { setError(problem.message); return null; }
  }
  const finish = (suffix, submitted) => ({ draft: { key: `${key}:${suffix}`, submitted } });
  const updateAction = patch => setAction({ ...action, ...patch });
  function begin(kind, extra = {}) { if (action) { setError('Finish or discard the saved action draft below first.'); return; } setAction({ kind, baseRev: item.rev, ...extra }); }
  function beginReview() { begin('review', { sources: currentSources(item.sources, specs, questions), note: '', authority: authorityDraft(item.authority) }); }
  async function saveAction(event) {
    event.preventDefault();
    const base = { ticketId: item.id, expectedRev: action.baseRev };
    let op, input;
    if (action.kind === 'transition') { op = 'ticket.transition'; input = { ...base, to: action.to, ...(action.reason ? { reason: action.reason } : {}), ...(action.to === 'done' ? { completion: { markdown: action.markdown, references: lines(action.references) } } : {}) }; }
    if (action.kind === 'wait') { op = 'ticket.wait.set'; input = { ...base, reason: action.reason }; }
    if (action.kind === 'review') { op = 'ticket.sources.acknowledge'; input = { ...base, sources: action.sources, note: action.note, authority: action.authority }; }
    if (action.kind === 'link') { op = 'ticket.link'; input = { ...base, specId: action.specId || null, questionIds: action.questionIds, ...(action.reason ? { reason: action.reason } : {}) }; }
    await act(op, input, finish('action', action));
  }
  return <section className="detail planning-detail" aria-label={`Ticket details for ${item.id}`}><DetailTop item={item} expanded={expanded} onExpand={onExpand} onClose={onClose} noun="ticket"/><div className="detail-content">
    <div className="detail-kicker"><span>Implementation ticket</span><span className={`execution-state state-${item.state}`}>{STATES[item.state]}</span></div><h2>{item.title}</h2><div className="metadata"><span>{maps.find(map => map.id === item.mapId)?.title || 'Standalone ticket'}</span><span>Priority {item.priority}</span><span>{item.ready ? 'Ready to claim' : item.satisfiesDependency ? 'Satisfies dependencies' : `Revision ${item.rev}`}</span></div><TicketFlags ticket={item}/>
    {error ? <p className="form-error action-error" role="alert">{error}</p> : null}{saved ? <p className="save-status" role="status">{saved}</p> : null}{contentStorage || progressStorage || actionStorage ? <p className="form-error" role="alert">Browser draft storage is unavailable. Save or copy drafts before reloading.</p> : null}
    <ClaimNotice item={item} type="ticket" act={act} busy={busy}/>
    {item.blockedBy?.length ? <div className="blocker-callout"><span className="small-label">Prerequisites</span>{item.blockedBy.map(id => <button key={id} onClick={() => onSelect(id)}><span>{tickets.find(ticket => ticket.id === id)?.title || id}</span><Icon name="arrow" size={14}/></button>)}<p className="content-note muted">Includes prerequisites outside the current board filters.</p></div> : null}
    {item.wait ? <div className="blocker-callout"><span className="small-label">Explicit wait</span><p>{typeof item.wait === 'string' ? item.wait : item.wait.reason}</p><button className="button" disabled={busy} onClick={() => act('ticket.wait.clear', { ticketId: item.id, expectedRev: item.rev })}>Clear wait</button></div> : null}
    <div className="ticket-move"><label>Move ticket<select disabled={busy || Boolean(action)} aria-label="Move ticket" value="" onChange={event => onMove(item, event.target.value, item.rev)}><option value="">Choose next column</option>{MOVES[item.state].map(state => <option key={state} value={state}>{item.state === 'done' ? 'Reopen in Backlog' : STATES[state]}</option>)}</select></label>{!item.wait && item.state !== 'done' ? <button className="quiet-button" disabled={busy || Boolean(action)} onClick={() => begin('wait', { reason: '' })}>Set wait</button> : null}</div>
    <div className="section-heading"><h3>Scope and acceptance</h3><button className="quiet-button" disabled={busy || locked || Boolean(draft)} onClick={() => setDraft(contentDraft(item))}><Icon name="edit" size={13}/>Edit</button></div>
    {locked ? <p className="muted content-note">Return to Backlog before changing the scope or acceptance criteria.</p> : null}
    {draft ? <form className="planning-fields" onSubmit={event => { event.preventDefault(); act('ticket.update', { ticketId: item.id, expectedRev: draft.baseRev, patch: { title: draft.title, body: draft.body, acceptanceCriteria: draft.acceptanceCriteria, authority: draft.authorityEnabled ? draft.authority : null } }, finish('content', draft)); }}><label>Ticket title<input required maxLength={300} disabled={busy} value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })}/></label><Editor label="Ticket body Markdown" value={draft.body} disabled={busy} onChange={body => setDraft({ ...draft, body })}/><h3>Acceptance criteria</h3><Editor label="Acceptance criteria Markdown" value={draft.acceptanceCriteria} disabled={busy} onChange={acceptanceCriteria => setDraft({ ...draft, acceptanceCriteria })}/><label className="checkbox-field"><input type="checkbox" disabled={busy} checked={draft.authorityEnabled} onChange={event => setDraft({ ...draft, authorityEnabled: event.target.checked })}/>Record authority for this scope</label>{draft.authorityEnabled ? <AuthorityFields disabled={busy} value={draft.authority} onChange={authority => setDraft({ ...draft, authority })}/> : null}<PlanningConflict draft={draft} item={item} onReload={() => setDraft(contentDraft(item))} onMerge={() => setDraft({ ...draft, baseRev: item.rev })}/><div className="editor-actions"><button type="button" className="button" disabled={busy} onClick={() => setDraft(null)}>Discard scope draft</button><button type="submit" className="button primary" disabled={busy || locked || draft.baseRev !== item.rev}>Save scope</button></div></form> : <><Markdown value={item.body || 'No scope written yet.'}/><div className="section-heading"><h3>Acceptance criteria</h3></div><Markdown value={item.acceptanceCriteria || 'No acceptance criteria yet.'}/><Authority value={item.authority}/></>}
    <div className="section-heading"><h3>Progress and metadata</h3><button className="quiet-button" disabled={busy || Boolean(progress)} onClick={() => setProgress(progressDraft(item))}><Icon name="edit" size={13}/>Edit</button></div>
    {progress ? <form className="planning-fields" onSubmit={event => { event.preventDefault(); if (deferredProgress) { setError('Reopen this ticket before saving the unsaved progress and references. Your draft is preserved.'); return; } act('ticket.update', { ticketId: item.id, expectedRev: progress.baseRev, patch: metadataChange.patch }, finish('progress', progress)); }}><label>Labels, separated by commas<input disabled={busy} value={progress.labels} onChange={event => setProgress({ ...progress, labels: event.target.value })}/></label><label>Priority<input type="number" min="0" max="4" required disabled={busy} value={progress.priority} onChange={event => setProgress({ ...progress, priority: event.target.value })}/></label>{item.state !== 'done' || deferredProgress ? <><Editor label="Progress Markdown" disabled={busy} value={progress.progress} onChange={value => setProgress({ ...progress, progress: value })}/><label>Artifact references, one per line<textarea disabled={busy} value={progress.references} onChange={event => setProgress({ ...progress, references: event.target.value })}/></label></> : null}{deferredProgress ? <p className="form-error" role="alert">This draft includes unsaved progress or references. Reopen the ticket before saving them. Your draft is preserved.</p> : null}<PlanningConflict draft={progress} item={item} onReload={() => setProgress(progressDraft(item))} onMerge={() => setProgress({ ...progress, baseRev: item.rev })}/><div className="editor-actions"><button type="button" className="button" onClick={() => setProgress(null)}>Discard metadata draft</button><button type="submit" disabled={busy || progress.baseRev !== item.rev || Boolean(deferredProgress)} className="button primary">Save metadata</button></div></form> : <><div className="labels">{item.labels.map(label => <span className="label" key={label}>{label}</span>)}</div><Markdown value={item.progress || 'No progress note yet.'}/><References values={item.references}/></>}
    <div className="section-heading"><h3>Planning sources</h3><button className="quiet-button" disabled={busy || item.state === 'done' || Boolean(action)} onClick={() => begin('link', { specId: item.sources.spec?.specId || '', questionIds: item.sources.questions.map(source => source.questionId), reason: '' })}>Change sources</button></div>
    {item.sources.spec ? <button className="source-link" onClick={() => onSpec(item.sources.spec.specId)}><span>Spec · {specs.find(spec => spec.id === item.sources.spec.specId)?.title || item.sources.spec.specId}</span><span>Linked approval {item.sources.spec.revision ?? 'none'} · current {specs.find(spec => spec.id === item.sources.spec.specId)?.usableApproval ? specs.find(spec => spec.id === item.sources.spec.specId).acceptedRevision : 'no usable approval'}</span><Icon name="arrow" size={13}/></button> : null}
    {item.sources.questions.map(source => { const question = questions.find(question => question.id === source.questionId); return <button className="source-link" key={source.questionId} onClick={() => question && onQuestion(question)}><span>{question?.title || source.questionId}</span><span>{maps.find(map => map.id === question?.mapId)?.title || question?.mapId || 'Question'} · linked answer {source.revision ?? 'none'} · current {question?.state === 'resolved' ? question.answer?.revision ?? 'none' : 'unresolved'}</span><Icon name="arrow" size={13}/></button>; })}
    {!item.sources.spec && !item.sources.questions.length ? <p className="muted content-note">Standalone scope. No planning sources linked.</p> : null}<SourceIssues issues={item.sourceIssues}/>
    {item.needsSourceReview || item.sourceIssues?.length ? <div className="source-review-notice"><p>Review the changed sources and dependent work before proceeding.</p><button disabled={busy || item.state === 'done' || Boolean(action)} className="button" onClick={beginReview}>Review current sources</button>{item.state === 'done' ? <p className="muted content-note">Reopen this ticket before acknowledging changed sources.</p> : null}</div> : null}
    {item.sourceReview ? <details className="source-review-history"><summary>Last source review</summary><Markdown value={item.sourceReview.note}/><Authority value={item.sourceReview.authority}/></details> : null}
    <div className="section-heading"><h3>Ticket connections</h3><span>{connections.length}</span></div><div className="connections">{connections.map(link => { const other = tickets.find(ticket => ticket.id === (link.from === item.id ? link.to : link.from)); if (!other) return null; const name = link.kind === 'related' ? 'Related to' : link.kind === 'parent' ? link.from === item.id ? 'Parent of' : 'Child of' : link.from === item.id ? 'Blocks' : 'Blocked by'; return <div className="connection" key={`${link.kind}:${link.from}:${link.to}`}><button className="connection-main" onClick={() => onSelect(other.id)}><span className="relationship">{name}</span><span>{other.title}</span></button><button disabled={busy} className="remove-link" aria-label={`Remove ${name} ${other.id}`} onClick={() => act('ticket.relationship.remove', { ...link, expectedFromRev: link.from === item.id ? item.rev : other.rev, expectedToRev: link.to === item.id ? item.rev : other.rev })}>×</button></div>; })}</div>
    <form className="connection-form" onSubmit={event => { event.preventDefault(); const other = tickets.find(ticket => ticket.id === target); if (!other) return; const reverse = relation === 'blocked-by'; act('ticket.relationship.add', { kind: reverse ? 'blocks' : relation, from: reverse ? other.id : item.id, to: reverse ? item.id : other.id, expectedFromRev: reverse ? other.rev : item.rev, expectedToRev: reverse ? item.rev : other.rev }, null, () => setTarget('')); }}><select aria-label="Ticket connection type" disabled={busy} value={relation} onChange={event => setRelation(event.target.value)}><option value="blocked-by">This ticket is blocked by</option><option value="blocks">This ticket blocks</option><option value="parent">This ticket is parent of</option><option value="related">Related to</option></select><select aria-label="Connect to ticket" required disabled={busy} value={target} onChange={event => setTarget(event.target.value)}><option value="">Choose a workspace ticket</option>{tickets.filter(ticket => ticket.id !== item.id).map(ticket => <option key={ticket.id} value={ticket.id}>{ticket.title}</option>)}</select><button disabled={busy || !target} type="submit" className="button">Add connection</button></form>
    {item.completion ? <section className="accepted-answer"><div className="section-heading"><h3>Completion evidence</h3></div><Markdown value={item.completion.markdown}/><References values={item.completion.references}/></section> : null}<TicketHistory item={item} query={query}/>
    {action ? <form ref={actionRef} className="answer-form planning-fields ticket-action" onSubmit={saveAction}><div className="section-heading"><h3>{action.kind === 'transition' ? `${item.state === 'done' ? 'Reopen in' : 'Move to'} ${STATES[action.to]}` : action.kind === 'review' ? 'Acknowledge current sources' : action.kind === 'wait' ? 'Set an explicit wait' : 'Change planning sources'}</h3></div>
      {action.kind === 'transition' ? <><p className="muted content-note">The server checks authority, sources, prerequisites, waits, and claims before moving.</p>{action.to === 'done' ? <><Editor label="Completion evidence Markdown" disabled={busy} value={action.markdown} onChange={markdown => updateAction({ markdown })}/><label>Completion references, one per line<textarea disabled={busy} value={action.references} onChange={event => updateAction({ references: event.target.value })}/></label></> : null}<label>{item.state === 'done' ? 'Reopen reason' : 'Move reason'}<textarea required={item.state === 'done' || item.state === 'review' && action.to === 'in-progress'} disabled={busy} value={action.reason} onChange={event => updateAction({ reason: event.target.value })}/></label></> : null}
      {action.kind === 'wait' ? <label>Wait reason<textarea required disabled={busy} value={action.reason} onChange={event => updateAction({ reason: event.target.value })}/></label> : null}
      {action.kind === 'review' ? <><p className="muted content-note">This acknowledges these exact stored revisions. It preserves the column, wait, and completion requirements.</p><SourceVersions sources={action.sources} questions={questions} specs={specs}/><label>Review note<textarea required disabled={busy} value={action.note} onChange={event => updateAction({ note: event.target.value })}/></label><AuthorityFields value={action.authority} disabled={busy} onChange={authority => updateAction({ authority })}/></> : null}
      {action.kind === 'link' ? <><label>Spec<select disabled={busy} value={action.specId} onChange={event => updateAction({ specId: event.target.value })}><option value="">No spec</option>{specs.map(spec => <option key={spec.id} value={spec.id}>{spec.title} · {spec.state}</option>)}</select></label><SourcePicker questions={questions} maps={maps} questionIds={action.questionIds} onChange={questionIds => updateAction({ questionIds })} disabled={busy}/><label>Source change reason<textarea required={['in-progress', 'review'].includes(item.state)} disabled={busy} value={action.reason} onChange={event => updateAction({ reason: event.target.value })}/></label></> : null}
      <PlanningConflict draft={action} item={item} onMerge={() => updateAction({ baseRev: item.rev, ...(action.kind === 'review' ? { sources: currentSources(item.sources, specs, questions) } : {}) })} mergeLabel={action.kind === 'review' ? 'Review latest source revisions' : 'Review action against current revision'}/><div className="editor-actions"><button type="button" className="button" disabled={busy} onClick={() => setAction(null)}>Discard action draft</button><button type="submit" className="button primary" disabled={busy || action.baseRev !== item.rev || action.kind === 'transition' && action.to === 'done' && !action.markdown.trim()}>Confirm {action.kind === 'transition' ? 'move' : action.kind === 'review' ? 'source review' : action.kind === 'wait' ? 'wait' : 'source links'}</button></div>
    </form> : null}
  </div></section>;
}
